language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

matrix:
    allow_failures:
        - php: hhvm

install:
  - composer install

script:
  - if [[ $TRAVIS_PHP_VERSION != "5.2" ]]; then bin/phpunit; else phpunit; fi

notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change
